version: '3'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=${DRONE_GITEA_URL}
#      - DRONE_GITEA_CLIENT=${DRONE_GITEA_CLIENT}
#      - DRONE_GITEA_SECRET=${DRONE_GITEA_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
    networks:
      - reverseproxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=drone-server"
      - "traefik.frontend.rule=Host:${DRONE_DOMAIN}"
      - "traefik.docker.network=traefik_reverseproxy"
      - "traefik.port=8000"

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}

networks:
    reverseproxy:
        external:
            name: traefik_reverseproxy
